from typing import Optional

import json

import google.generativeai as genai

from pydantic import BaseModel


class GenaiAddressParseResult(BaseModel):
    success: bool = False
    street: Optional[str] = None
    number: Optional[str] = None
    apartment: Optional[str] = None
    neighborhood: Optional[str] = None
    city: Optional[str] = None
    province: Optional[str] = None
    country: Optional[str] = None
    pass


class GenaiAddressParser:
    BASE_PROMPT = """
        dado un texto, ayudame a extraer la dirección de la persona que se menciona en el texto, si es que se menciona alguna.
        Si no se puede extraer la dirección, devolver success=false
        un ejemplo de texto es: "Hola, soy Juan Perez, vivo en Av. Rivadavia 1234"
        y la respuesta esperada es: { "street": "Av. Rivadavia", "number": "1234", "success": true }
        tambien puede ocurrir que podamos obtener la calle pero no el numero, en ese caso devolver success=false pero con la calle
        si puedes obtener mas datos, como el barrio, la ciudad, la provincia, etc, devuelvelos tambien.
        ---
        dado texto:  "%s"
        cual crees que es la dirección de la persona que se menciona en el texto, devuelmelo en el formato json? 
    """

    def __init__(self, model: genai.GenerativeModel):
        self.model = model

    def parse(self, address) -> GenaiAddressParseResult:
        prompt = self.BASE_PROMPT % (address)
        result = self.model.generate_content(prompt)
        # print text generated by the model
        text = result.text
        # remove first line and last line and parse json
        text = text.split("\n")[1:-1]
        text = "\n".join(text)
        print("text: ", text)
        json_result = json.loads(text)
        return GenaiAddressParseResult(**json_result)


if __name__ == '__main__':
    SAMPLES = [
        "Av. Remedios de Escalada de San Martin 2639, B1822 Valentín Alsina, Provincia de Buenos Aires, Argentina",
        "CHO, Viamonte 2200, B1822 Lanús, Provincia de Buenos Aires, Argentina",
        "Liniers, Valentín Alsina, Provincia de Buenos Aires, Argentina"
    ]

    GOOGLE_API_KEY = "AIzaSyBHNwhGR9g291lJ9IBNtUQQ97nq25vaQfs"  # ernestsimionato1
    genai.configure(api_key=GOOGLE_API_KEY)
    model = genai.GenerativeModel("gemini-pro")
    address_parser = GenaiAddressParser(model)

    for sample in SAMPLES:
        result = address_parser.parse(sample)
        print("result: ", result)

"""
Coronel D Elia 3895, Provincia de Buenos Aires
Avenida Tte Gral Juan Domingo Perón 3000, Buenos Aires
Av. Remedios de Escalada de San Martín 2639, B1822 Valentín Alsina, Provincia de Buenos Aires, Argentina
CHO, Viamonte 2200, B1822 Lanús, Provincia de Buenos Aires, Argentina
Liniers, Valentín Alsina, Provincia de Buenos Aires, Argentina
"""
